export function camelToKebab(camelCasedName: string): string {
  if (!isCamelCased(camelCasedName)) throw new Error(`Not a camelCased name: ${camelCasedName}`);
  return hyphenateStyleName(camelCasedName);
}

function isCamelCased(someName: string): boolean {
  return camelCasePattern.test(someName);
}

const camelCasePattern = /([a-z])([A-Z]{1})([a-z])/g;
const uppercasePattern = /([A-Z])/g;
const msPattern = /^ms-/;

// CSSStyleDeclaration
/**
 * Note that this is clearly from react open source project. Thank you a lot.
 * https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/shared/hyphenateStyleName.js
 * 
 * Hyphenates a camelcased CSS property name, for example:
 *
 *   > hyphenateStyleName('backgroundColor')
 *   < "background-color"
 *   > hyphenateStyleName('MozTransition')
 *   < "-moz-transition"
 *   > hyphenateStyleName('msTransition')
 *   < "-ms-transition"
 *
 * As Modernizr suggests (http://modernizr.com/docs/#prefixed), an `ms` prefix
 * is converted to `-ms-`.
 */
export function hyphenateStyleName(name: string): string {
  return name
    .replace(uppercasePattern, '-$1')
    .toLowerCase()
    .replace(msPattern, '-ms-');
}

/**
 * {
    "0": "accent-color",
    "1": "align-content",
    "2": "align-items",
    "3": "align-self",
    "4": "alignment-baseline",
    "5": "animation-composition",
    "6": "animation-delay",
    "7": "animation-direction",
    "8": "animation-duration",
    "9": "animation-fill-mode",
    "10": "animation-iteration-count",
    "11": "animation-name",
    "12": "animation-play-state",
    "13": "animation-range-end",
    "14": "animation-range-start",
    "15": "animation-timeline",
    "16": "animation-timing-function",
    "17": "app-region",
    "18": "appearance",
    "19": "backdrop-filter",
    "20": "backface-visibility",
    "21": "background-attachment",
    "22": "background-blend-mode",
    "23": "background-clip",
    "24": "background-color",
    "25": "background-image",
    "26": "background-origin",
    "27": "background-position",
    "28": "background-repeat",
    "29": "background-size",
    "30": "baseline-shift",
    "31": "baseline-source",
    "32": "block-size",
    "33": "border-block-end-color",
    "34": "border-block-end-style",
    "35": "border-block-end-width",
    "36": "border-block-start-color",
    "37": "border-block-start-style",
    "38": "border-block-start-width",
    "39": "border-bottom-color",
    "40": "border-bottom-left-radius",
    "41": "border-bottom-right-radius",
    "42": "border-bottom-style",
    "43": "border-bottom-width",
    "44": "border-collapse",
    "45": "border-end-end-radius",
    "46": "border-end-start-radius",
    "47": "border-image-outset",
    "48": "border-image-repeat",
    "49": "border-image-slice",
    "50": "border-image-source",
    "51": "border-image-width",
    "52": "border-inline-end-color",
    "53": "border-inline-end-style",
    "54": "border-inline-end-width",
    "55": "border-inline-start-color",
    "56": "border-inline-start-style",
    "57": "border-inline-start-width",
    "58": "border-left-color",
    "59": "border-left-style",
    "60": "border-left-width",
    "61": "border-right-color",
    "62": "border-right-style",
    "63": "border-right-width",
    "64": "border-start-end-radius",
    "65": "border-start-start-radius",
    "66": "border-top-color",
    "67": "border-top-left-radius",
    "68": "border-top-right-radius",
    "69": "border-top-style",
    "70": "border-top-width",
    "71": "bottom",
    "72": "box-shadow",
    "73": "box-sizing",
    "74": "break-after",
    "75": "break-before",
    "76": "break-inside",
    "77": "buffered-rendering",
    "78": "caption-side",
    "79": "caret-color",
    "80": "clear",
    "81": "clip",
    "82": "clip-path",
    "83": "clip-rule",
    "84": "color",
    "85": "color-interpolation",
    "86": "color-interpolation-filters",
    "87": "color-rendering",
    "88": "column-count",
    "89": "column-gap",
    "90": "column-rule-color",
    "91": "column-rule-style",
    "92": "column-rule-width",
    "93": "column-span",
    "94": "column-width",
    "95": "contain-intrinsic-block-size",
    "96": "contain-intrinsic-height",
    "97": "contain-intrinsic-inline-size",
    "98": "contain-intrinsic-size",
    "99": "contain-intrinsic-width",
    "100": "container-name",
    "101": "container-type",
    "102": "content",
    "103": "cursor",
    "104": "cx",
    "105": "cy",
    "106": "d",
    "107": "direction",
    "108": "display",
    "109": "dominant-baseline",
    "110": "empty-cells",
    "111": "fill",
    "112": "fill-opacity",
    "113": "fill-rule",
    "114": "filter",
    "115": "flex-basis",
    "116": "flex-direction",
    "117": "flex-grow",
    "118": "flex-shrink",
    "119": "flex-wrap",
    "120": "float",
    "121": "flood-color",
    "122": "flood-opacity",
    "123": "font-family",
    "124": "font-kerning",
    "125": "font-optical-sizing",
    "126": "font-palette",
    "127": "font-size",
    "128": "font-stretch",
    "129": "font-style",
    "130": "font-synthesis-small-caps",
    "131": "font-synthesis-style",
    "132": "font-synthesis-weight",
    "133": "font-variant",
    "134": "font-variant-alternates",
    "135": "font-variant-caps",
    "136": "font-variant-east-asian",
    "137": "font-variant-ligatures",
    "138": "font-variant-numeric",
    "139": "font-variant-position",
    "140": "font-weight",
    "141": "grid-auto-columns",
    "142": "grid-auto-flow",
    "143": "grid-auto-rows",
    "144": "grid-column-end",
    "145": "grid-column-start",
    "146": "grid-row-end",
    "147": "grid-row-start",
    "148": "grid-template-areas",
    "149": "grid-template-columns",
    "150": "grid-template-rows",
    "151": "height",
    "152": "hyphenate-character",
    "153": "hyphenate-limit-chars",
    "154": "hyphens",
    "155": "image-orientation",
    "156": "image-rendering",
    "157": "initial-letter",
    "158": "inline-size",
    "159": "inset-block-end",
    "160": "inset-block-start",
    "161": "inset-inline-end",
    "162": "inset-inline-start",
    "163": "isolation",
    "164": "justify-content",
    "165": "justify-items",
    "166": "justify-self",
    "167": "left",
    "168": "letter-spacing",
    "169": "lighting-color",
    "170": "line-break",
    "171": "line-height",
    "172": "list-style-image",
    "173": "list-style-position",
    "174": "list-style-type",
    "175": "margin-block-end",
    "176": "margin-block-start",
    "177": "margin-bottom",
    "178": "margin-inline-end",
    "179": "margin-inline-start",
    "180": "margin-left",
    "181": "margin-right",
    "182": "margin-top",
    "183": "marker-end",
    "184": "marker-mid",
    "185": "marker-start",
    "186": "mask-clip",
    "187": "mask-composite",
    "188": "mask-image",
    "189": "mask-mode",
    "190": "mask-origin",
    "191": "mask-position",
    "192": "mask-repeat",
    "193": "mask-size",
    "194": "mask-type",
    "195": "math-depth",
    "196": "math-shift",
    "197": "math-style",
    "198": "max-block-size",
    "199": "max-height",
    "200": "max-inline-size",
    "201": "max-width",
    "202": "min-block-size",
    "203": "min-height",
    "204": "min-inline-size",
    "205": "min-width",
    "206": "mix-blend-mode",
    "207": "object-fit",
    "208": "object-position",
    "209": "object-view-box",
    "210": "offset-anchor",
    "211": "offset-distance",
    "212": "offset-path",
    "213": "offset-position",
    "214": "offset-rotate",
    "215": "opacity",
    "216": "order",
    "217": "orphans",
    "218": "outline-color",
    "219": "outline-offset",
    "220": "outline-style",
    "221": "outline-width",
    "222": "overflow-anchor",
    "223": "overflow-clip-margin",
    "224": "overflow-wrap",
    "225": "overflow-x",
    "226": "overflow-y",
    "227": "overlay",
    "228": "overscroll-behavior-block",
    "229": "overscroll-behavior-inline",
    "230": "padding-block-end",
    "231": "padding-block-start",
    "232": "padding-bottom",
    "233": "padding-inline-end",
    "234": "padding-inline-start",
    "235": "padding-left",
    "236": "padding-right",
    "237": "padding-top",
    "238": "paint-order",
    "239": "perspective",
    "240": "perspective-origin",
    "241": "pointer-events",
    "242": "position",
    "243": "r",
    "244": "resize",
    "245": "right",
    "246": "rotate",
    "247": "row-gap",
    "248": "ruby-position",
    "249": "rx",
    "250": "ry",
    "251": "scale",
    "252": "scroll-behavior",
    "253": "scroll-margin-block-end",
    "254": "scroll-margin-block-start",
    "255": "scroll-margin-inline-end",
    "256": "scroll-margin-inline-start",
    "257": "scroll-padding-block-end",
    "258": "scroll-padding-block-start",
    "259": "scroll-padding-inline-end",
    "260": "scroll-padding-inline-start",
    "261": "scroll-timeline-axis",
    "262": "scroll-timeline-name",
    "263": "scrollbar-gutter",
    "264": "shape-image-threshold",
    "265": "shape-margin",
    "266": "shape-outside",
    "267": "shape-rendering",
    "268": "speak",
    "269": "stop-color",
    "270": "stop-opacity",
    "271": "stroke",
    "272": "stroke-dasharray",
    "273": "stroke-dashoffset",
    "274": "stroke-linecap",
    "275": "stroke-linejoin",
    "276": "stroke-miterlimit",
    "277": "stroke-opacity",
    "278": "stroke-width",
    "279": "tab-size",
    "280": "table-layout",
    "281": "text-align",
    "282": "text-align-last",
    "283": "text-anchor",
    "284": "text-decoration",
    "285": "text-decoration-color",
    "286": "text-decoration-line",
    "287": "text-decoration-skip-ink",
    "288": "text-decoration-style",
    "289": "text-emphasis-color",
    "290": "text-emphasis-position",
    "291": "text-emphasis-style",
    "292": "text-indent",
    "293": "text-overflow",
    "294": "text-rendering",
    "295": "text-shadow",
    "296": "text-size-adjust",
    "297": "text-transform",
    "298": "text-underline-position",
    "299": "text-wrap",
    "300": "timeline-scope",
    "301": "top",
    "302": "touch-action",
    "303": "transform",
    "304": "transform-origin",
    "305": "transform-style",
    "306": "transition-behavior",
    "307": "transition-delay",
    "308": "transition-duration",
    "309": "transition-property",
    "310": "transition-timing-function",
    "311": "translate",
    "312": "unicode-bidi",
    "313": "user-select",
    "314": "vector-effect",
    "315": "vertical-align",
    "316": "view-timeline-axis",
    "317": "view-timeline-inset",
    "318": "view-timeline-name",
    "319": "view-transition-name",
    "320": "visibility",
    "321": "white-space-collapse",
    "322": "widows",
    "323": "width",
    "324": "will-change",
    "325": "word-break",
    "326": "word-spacing",
    "327": "writing-mode",
    "328": "x",
    "329": "y",
    "330": "z-index",
    "331": "zoom",
    "332": "-webkit-border-horizontal-spacing",
    "333": "-webkit-border-image",
    "334": "-webkit-border-vertical-spacing",
    "335": "-webkit-box-align",
    "336": "-webkit-box-decoration-break",
    "337": "-webkit-box-direction",
    "338": "-webkit-box-flex",
    "339": "-webkit-box-ordinal-group",
    "340": "-webkit-box-orient",
    "341": "-webkit-box-pack",
    "342": "-webkit-box-reflect",
    "343": "-webkit-font-smoothing",
    "344": "-webkit-line-break",
    "345": "-webkit-line-clamp",
    "346": "-webkit-locale",
    "347": "-webkit-mask-box-image",
    "348": "-webkit-mask-box-image-outset",
    "349": "-webkit-mask-box-image-repeat",
    "350": "-webkit-mask-box-image-slice",
    "351": "-webkit-mask-box-image-source",
    "352": "-webkit-mask-box-image-width",
    "353": "-webkit-print-color-adjust",
    "354": "-webkit-rtl-ordering",
    "355": "-webkit-tap-highlight-color",
    "356": "-webkit-text-combine",
    "357": "-webkit-text-decorations-in-effect",
    "358": "-webkit-text-fill-color",
    "359": "-webkit-text-orientation",
    "360": "-webkit-text-security",
    "361": "-webkit-text-stroke-color",
    "362": "-webkit-text-stroke-width",
    "363": "-webkit-user-drag",
    "364": "-webkit-user-modify",
    "365": "-webkit-writing-mode",
    "accentColor": "rgb(94, 158, 255)",
    "additiveSymbols": "",
    "alignContent": "normal",
    "alignItems": "normal",
    "alignSelf": "auto",
    "alignmentBaseline": "auto",
    "all": "",
    "animation": "1e-05s ease 0s 1 normal none running none",
    "animationComposition": "replace",
    "animationDelay": "0s",
    "animationDirection": "normal",
    "animationDuration": "1e-05s",
    "animationFillMode": "none",
    "animationIterationCount": "1",
    "animationName": "none",
    "animationPlayState": "running",
    "animationRange": "normal",
    "animationRangeEnd": "normal",
    "animationRangeStart": "normal",
    "animationTimeline": "auto",
    "animationTimingFunction": "ease",
    "appRegion": "none",
    "appearance": "none",
    "ascentOverride": "",
    "aspectRatio": "auto",
    "backdropFilter": "none",
    "backfaceVisibility": "visible",
    "background": "rgb(27, 27, 27) none repeat scroll 0% 0% / auto padding-box border-box",
    "backgroundAttachment": "scroll",
    "backgroundBlendMode": "normal",
    "backgroundClip": "border-box",
    "backgroundColor": "rgb(27, 27, 27)",
    "backgroundImage": "none",
    "backgroundOrigin": "padding-box",
    "backgroundPosition": "0% 0%",
    "backgroundPositionX": "0%",
    "backgroundPositionY": "0%",
    "backgroundRepeat": "repeat",
    "backgroundSize": "auto",
    "basePalette": "",
    "baselineShift": "0px",
    "baselineSource": "auto",
    "blockSize": "4622.47px",
    "border": "0px none rgb(255, 255, 255)",
    "borderBlock": "0px none rgb(255, 255, 255)",
    "borderBlockColor": "rgb(255, 255, 255)",
    "borderBlockEnd": "0px none rgb(255, 255, 255)",
    "borderBlockEndColor": "rgb(255, 255, 255)",
    "borderBlockEndStyle": "none",
    "borderBlockEndWidth": "0px",
    "borderBlockStart": "0px none rgb(255, 255, 255)",
    "borderBlockStartColor": "rgb(255, 255, 255)",
    "borderBlockStartStyle": "none",
    "borderBlockStartWidth": "0px",
    "borderBlockStyle": "none",
    "borderBlockWidth": "0px",
    "borderBottom": "0px none rgb(255, 255, 255)",
    "borderBottomColor": "rgb(255, 255, 255)",
    "borderBottomLeftRadius": "0px",
    "borderBottomRightRadius": "0px",
    "borderBottomStyle": "none",
    "borderBottomWidth": "0px",
    "borderCollapse": "separate",
    "borderColor": "rgb(255, 255, 255)",
    "borderEndEndRadius": "0px",
    "borderEndStartRadius": "0px",
    "borderImage": "none",
    "borderImageOutset": "0",
    "borderImageRepeat": "stretch",
    "borderImageSlice": "100%",
    "borderImageSource": "none",
    "borderImageWidth": "1",
    "borderInline": "0px none rgb(255, 255, 255)",
    "borderInlineColor": "rgb(255, 255, 255)",
    "borderInlineEnd": "0px none rgb(255, 255, 255)",
    "borderInlineEndColor": "rgb(255, 255, 255)",
    "borderInlineEndStyle": "none",
    "borderInlineEndWidth": "0px",
    "borderInlineStart": "0px none rgb(255, 255, 255)",
    "borderInlineStartColor": "rgb(255, 255, 255)",
    "borderInlineStartStyle": "none",
    "borderInlineStartWidth": "0px",
    "borderInlineStyle": "none",
    "borderInlineWidth": "0px",
    "borderLeft": "0px none rgb(255, 255, 255)",
    "borderLeftColor": "rgb(255, 255, 255)",
    "borderLeftStyle": "none",
    "borderLeftWidth": "0px",
    "borderRadius": "0px",
    "borderRight": "0px none rgb(255, 255, 255)",
    "borderRightColor": "rgb(255, 255, 255)",
    "borderRightStyle": "none",
    "borderRightWidth": "0px",
    "borderSpacing": "0px 0px",
    "borderStartEndRadius": "0px",
    "borderStartStartRadius": "0px",
    "borderStyle": "none",
    "borderTop": "0px none rgb(255, 255, 255)",
    "borderTopColor": "rgb(255, 255, 255)",
    "borderTopLeftRadius": "0px",
    "borderTopRightRadius": "0px",
    "borderTopStyle": "none",
    "borderTopWidth": "0px",
    "borderWidth": "0px",
    "bottom": "auto",
    "boxShadow": "none",
    "boxSizing": "border-box",
    "breakAfter": "auto",
    "breakBefore": "auto",
    "breakInside": "auto",
    "bufferedRendering": "auto",
    "captionSide": "top",
    "caretColor": "rgb(255, 255, 255)",
    "clear": "none",
    "clip": "auto",
    "clipPath": "none",
    "clipRule": "nonzero",
    "color": "rgb(255, 255, 255)",
    "colorInterpolation": "srgb",
    "colorInterpolationFilters": "linearrgb",
    "colorRendering": "auto",
    "colorScheme": "dark",
    "columnCount": "auto",
    "columnFill": "balance",
    "columnGap": "normal",
    "columnRule": "0px none rgb(255, 255, 255)",
    "columnRuleColor": "rgb(255, 255, 255)",
    "columnRuleStyle": "none",
    "columnRuleWidth": "0px",
    "columnSpan": "none",
    "columnWidth": "auto",
    "columns": "auto auto",
    "contain": "none",
    "containIntrinsicBlockSize": "none",
    "containIntrinsicHeight": "none",
    "containIntrinsicInlineSize": "none",
    "containIntrinsicSize": "none",
    "containIntrinsicWidth": "none",
    "container": "none",
    "containerName": "none",
    "containerType": "normal",
    "content": "normal",
    "contentVisibility": "visible",
    "counterIncrement": "none",
    "counterReset": "none",
    "counterSet": "none",
    "cursor": "auto",
    "cx": "0px",
    "cy": "0px",
    "d": "none",
    "descentOverride": "",
    "direction": "ltr",
    "display": "block",
    "dominantBaseline": "auto",
    "emptyCells": "show",
    "fallback": "",
    "fill": "rgb(0, 0, 0)",
    "fillOpacity": "1",
    "fillRule": "nonzero",
    "filter": "none",
    "flex": "0 1 auto",
    "flexBasis": "auto",
    "flexDirection": "row",
    "flexFlow": "row nowrap",
    "flexGrow": "0",
    "flexShrink": "1",
    "flexWrap": "nowrap",
    "float": "none",
    "floodColor": "rgb(0, 0, 0)",
    "floodOpacity": "1",
    "font": "16px / 28px Inter, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", sans-serif",
    "fontDisplay": "",
    "fontFamily": "Inter, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", sans-serif",
    "fontFeatureSettings": "normal",
    "fontKerning": "auto",
    "fontOpticalSizing": "auto",
    "fontPalette": "normal",
    "fontSize": "16px",
    "fontStretch": "100%",
    "fontStyle": "normal",
    "fontSynthesis": "weight style small-caps",
    "fontSynthesisSmallCaps": "auto",
    "fontSynthesisStyle": "auto",
    "fontSynthesisWeight": "auto",
    "fontVariant": "normal",
    "fontVariantAlternates": "normal",
    "fontVariantCaps": "normal",
    "fontVariantEastAsian": "normal",
    "fontVariantLigatures": "normal",
    "fontVariantNumeric": "normal",
    "fontVariantPosition": "normal",
    "fontVariationSettings": "normal",
    "fontWeight": "400",
    "forcedColorAdjust": "auto",
    "gap": "normal",
    "grid": "none / none / none / row / auto / auto",
    "gridArea": "auto",
    "gridAutoColumns": "auto",
    "gridAutoFlow": "row",
    "gridAutoRows": "auto",
    "gridColumn": "auto",
    "gridColumnEnd": "auto",
    "gridColumnGap": "normal",
    "gridColumnStart": "auto",
    "gridGap": "normal normal",
    "gridRow": "auto",
    "gridRowEnd": "auto",
    "gridRowGap": "normal",
    "gridRowStart": "auto",
    "gridTemplate": "none",
    "gridTemplateAreas": "none",
    "gridTemplateColumns": "none",
    "gridTemplateRows": "none",
    "height": "4622.47px",
    "hyphenateCharacter": "auto",
    "hyphenateLimitChars": "auto",
    "hyphens": "manual",
    "imageOrientation": "from-image",
    "imageRendering": "auto",
    "inherits": "",
    "initialLetter": "normal",
    "initialValue": "",
    "inlineSize": "2543px",
    "inset": "auto",
    "insetBlock": "auto",
    "insetBlockEnd": "auto",
    "insetBlockStart": "auto",
    "insetInline": "auto",
    "insetInlineEnd": "auto",
    "insetInlineStart": "auto",
    "isolation": "auto",
    "justifyContent": "normal",
    "justifyItems": "normal",
    "justifySelf": "auto",
    "left": "auto",
    "letterSpacing": "normal",
    "lightingColor": "rgb(255, 255, 255)",
    "lineBreak": "auto",
    "lineGapOverride": "",
    "lineHeight": "28px",
    "listStyle": "outside none disc",
    "listStyleImage": "none",
    "listStylePosition": "outside",
    "listStyleType": "disc",
    "margin": "0px",
    "marginBlock": "0px",
    "marginBlockEnd": "0px",
    "marginBlockStart": "0px",
    "marginBottom": "0px",
    "marginInline": "0px",
    "marginInlineEnd": "0px",
    "marginInlineStart": "0px",
    "marginLeft": "0px",
    "marginRight": "0px",
    "marginTop": "0px",
    "marker": "none",
    "markerEnd": "none",
    "markerMid": "none",
    "markerStart": "none",
    "mask": "none",
    "maskClip": "border-box",
    "maskComposite": "add",
    "maskImage": "none",
    "maskMode": "match-source",
    "maskOrigin": "border-box",
    "maskPosition": "0% 0%",
    "maskRepeat": "repeat",
    "maskSize": "auto",
    "maskType": "luminance",
    "mathDepth": "0",
    "mathShift": "normal",
    "mathStyle": "normal",
    "maxBlockSize": "none",
    "maxHeight": "none",
    "maxInlineSize": "none",
    "maxWidth": "none",
    "minBlockSize": "0px",
    "minHeight": "0px",
    "minInlineSize": "0px",
    "minWidth": "0px",
    "mixBlendMode": "normal",
    "negative": "",
    "objectFit": "fill",
    "objectPosition": "50% 50%",
    "objectViewBox": "none",
    "offset": "none 0px auto 0deg",
    "offsetAnchor": "auto",
    "offsetDistance": "0px",
    "offsetPath": "none",
    "offsetPosition": "normal",
    "offsetRotate": "auto 0deg",
    "opacity": "1",
    "order": "0",
    "orphans": "2",
    "outline": "rgb(255, 255, 255) none 0px",
    "outlineColor": "rgb(255, 255, 255)",
    "outlineOffset": "0px",
    "outlineStyle": "none",
    "outlineWidth": "0px",
    "overflow": "visible",
    "overflowAnchor": "auto",
    "overflowClipMargin": "0px",
    "overflowWrap": "normal",
    "overflowX": "visible",
    "overflowY": "visible",
    "overlay": "none",
    "overrideColors": "",
    "overscrollBehavior": "auto",
    "overscrollBehaviorBlock": "auto",
    "overscrollBehaviorInline": "auto",
    "overscrollBehaviorX": "auto",
    "overscrollBehaviorY": "auto",
    "pad": "",
    "padding": "0px",
    "paddingBlock": "0px",
    "paddingBlockEnd": "0px",
    "paddingBlockStart": "0px",
    "paddingBottom": "0px",
    "paddingInline": "0px",
    "paddingInlineEnd": "0px",
    "paddingInlineStart": "0px",
    "paddingLeft": "0px",
    "paddingRight": "0px",
    "paddingTop": "0px",
    "page": "auto",
    "pageBreakAfter": "auto",
    "pageBreakBefore": "auto",
    "pageBreakInside": "auto",
    "pageOrientation": "",
    "paintOrder": "normal",
    "perspective": "none",
    "perspectiveOrigin": "1271.5px 2311.23px",
    "placeContent": "normal",
    "placeItems": "normal",
    "placeSelf": "auto",
    "pointerEvents": "auto",
    "position": "static",
    "prefix": "",
    "quotes": "auto",
    "r": "0px",
    "range": "",
    "resize": "none",
    "right": "auto",
    "rotate": "none",
    "rowGap": "normal",
    "rubyPosition": "over",
    "rx": "auto",
    "ry": "auto",
    "scale": "none",
    "scrollBehavior": "auto",
    "scrollMargin": "0px",
    "scrollMarginBlock": "0px",
    "scrollMarginBlockEnd": "0px",
    "scrollMarginBlockStart": "0px",
    "scrollMarginBottom": "0px",
    "scrollMarginInline": "0px",
    "scrollMarginInlineEnd": "0px",
    "scrollMarginInlineStart": "0px",
    "scrollMarginLeft": "0px",
    "scrollMarginRight": "0px",
    "scrollMarginTop": "0px",
    "scrollPadding": "auto",
    "scrollPaddingBlock": "auto",
    "scrollPaddingBlockEnd": "auto",
    "scrollPaddingBlockStart": "auto",
    "scrollPaddingBottom": "auto",
    "scrollPaddingInline": "auto",
    "scrollPaddingInlineEnd": "auto",
    "scrollPaddingInlineStart": "auto",
    "scrollPaddingLeft": "auto",
    "scrollPaddingRight": "auto",
    "scrollPaddingTop": "auto",
    "scrollSnapAlign": "none",
    "scrollSnapStop": "normal",
    "scrollSnapType": "none",
    "scrollTimeline": "none",
    "scrollTimelineAxis": "block",
    "scrollTimelineName": "none",
    "scrollbarGutter": "auto",
    "shapeImageThreshold": "0",
    "shapeMargin": "0px",
    "shapeOutside": "none",
    "shapeRendering": "auto",
    "size": "",
    "sizeAdjust": "",
    "speak": "normal",
    "speakAs": "",
    "src": "",
    "stopColor": "rgb(0, 0, 0)",
    "stopOpacity": "1",
    "stroke": "none",
    "strokeDasharray": "none",
    "strokeDashoffset": "0px",
    "strokeLinecap": "butt",
    "strokeLinejoin": "miter",
    "strokeMiterlimit": "4",
    "strokeOpacity": "1",
    "strokeWidth": "1px",
    "suffix": "",
    "symbols": "",
    "syntax": "",
    "system": "",
    "tabSize": "8",
    "tableLayout": "auto",
    "textAlign": "start",
    "textAlignLast": "auto",
    "textAnchor": "start",
    "textCombineUpright": "none",
    "textDecoration": "none solid rgb(255, 255, 255)",
    "textDecorationColor": "rgb(255, 255, 255)",
    "textDecorationLine": "none",
    "textDecorationSkipInk": "auto",
    "textDecorationStyle": "solid",
    "textDecorationThickness": "auto",
    "textEmphasis": "none rgb(255, 255, 255)",
    "textEmphasisColor": "rgb(255, 255, 255)",
    "textEmphasisPosition": "over",
    "textEmphasisStyle": "none",
    "textIndent": "0px",
    "textOrientation": "mixed",
    "textOverflow": "clip",
    "textRendering": "optimizespeed",
    "textShadow": "none",
    "textSizeAdjust": "auto",
    "textTransform": "none",
    "textUnderlineOffset": "auto",
    "textUnderlinePosition": "auto",
    "textWrap": "wrap",
    "timelineScope": "none",
    "top": "auto",
    "touchAction": "auto",
    "transform": "none",
    "transformBox": "view-box",
    "transformOrigin": "1271.5px 2311.23px",
    "transformStyle": "flat",
    "transition": "all 1e-05s ease 0s",
    "transitionBehavior": "normal",
    "transitionDelay": "0s",
    "transitionDuration": "1e-05s",
    "transitionProperty": "all",
    "transitionTimingFunction": "ease",
    "translate": "none",
    "unicodeBidi": "normal",
    "unicodeRange": "",
    "userSelect": "auto",
    "vectorEffect": "none",
    "verticalAlign": "baseline",
    "viewTimeline": "none",
    "viewTimelineAxis": "block",
    "viewTimelineInset": "auto",
    "viewTimelineName": "none",
    "viewTransitionName": "none",
    "visibility": "visible",
    "webkitAlignContent": "normal",
    "webkitAlignItems": "normal",
    "webkitAlignSelf": "auto",
    "webkitAnimation": "1e-05s ease 0s 1 normal none running none",
    "webkitAnimationDelay": "0s",
    "webkitAnimationDirection": "normal",
    "webkitAnimationDuration": "1e-05s",
    "webkitAnimationFillMode": "none",
    "webkitAnimationIterationCount": "1",
    "webkitAnimationName": "none",
    "webkitAnimationPlayState": "running",
    "webkitAnimationTimingFunction": "ease",
    "webkitAppRegion": "none",
    "webkitAppearance": "none",
    "webkitBackfaceVisibility": "visible",
    "webkitBackgroundClip": "border-box",
    "webkitBackgroundOrigin": "padding-box",
    "webkitBackgroundSize": "auto",
    "webkitBorderAfter": "0px none rgb(255, 255, 255)",
    "webkitBorderAfterColor": "rgb(255, 255, 255)",
    "webkitBorderAfterStyle": "none",
    "webkitBorderAfterWidth": "0px",
    "webkitBorderBefore": "0px none rgb(255, 255, 255)",
    "webkitBorderBeforeColor": "rgb(255, 255, 255)",
    "webkitBorderBeforeStyle": "none",
    "webkitBorderBeforeWidth": "0px",
    "webkitBorderBottomLeftRadius": "0px",
    "webkitBorderBottomRightRadius": "0px",
    "webkitBorderEnd": "0px none rgb(255, 255, 255)",
    "webkitBorderEndColor": "rgb(255, 255, 255)",
    "webkitBorderEndStyle": "none",
    "webkitBorderEndWidth": "0px",
    "webkitBorderHorizontalSpacing": "0px",
    "webkitBorderImage": "none",
    "webkitBorderRadius": "0px",
    "webkitBorderStart": "0px none rgb(255, 255, 255)",
    "webkitBorderStartColor": "rgb(255, 255, 255)",
    "webkitBorderStartStyle": "none",
    "webkitBorderStartWidth": "0px",
    "webkitBorderTopLeftRadius": "0px",
    "webkitBorderTopRightRadius": "0px",
    "webkitBorderVerticalSpacing": "0px",
    "webkitBoxAlign": "stretch",
    "webkitBoxDecorationBreak": "slice",
    "webkitBoxDirection": "normal",
    "webkitBoxFlex": "0",
    "webkitBoxOrdinalGroup": "1",
    "webkitBoxOrient": "horizontal",
    "webkitBoxPack": "start",
    "webkitBoxReflect": "none",
    "webkitBoxShadow": "none",
    "webkitBoxSizing": "border-box",
    "webkitClipPath": "none",
    "webkitColumnBreakAfter": "auto",
    "webkitColumnBreakBefore": "auto",
    "webkitColumnBreakInside": "auto",
    "webkitColumnCount": "auto",
    "webkitColumnGap": "normal",
    "webkitColumnRule": "0px none rgb(255, 255, 255)",
    "webkitColumnRuleColor": "rgb(255, 255, 255)",
    "webkitColumnRuleStyle": "none",
    "webkitColumnRuleWidth": "0px",
    "webkitColumnSpan": "none",
    "webkitColumnWidth": "auto",
    "webkitColumns": "auto auto",
    "webkitFilter": "none",
    "webkitFlex": "0 1 auto",
    "webkitFlexBasis": "auto",
    "webkitFlexDirection": "row",
    "webkitFlexFlow": "row nowrap",
    "webkitFlexGrow": "0",
    "webkitFlexShrink": "1",
    "webkitFlexWrap": "nowrap",
    "webkitFontFeatureSettings": "normal",
    "webkitFontSmoothing": "auto",
    "webkitHyphenateCharacter": "auto",
    "webkitJustifyContent": "normal",
    "webkitLineBreak": "auto",
    "webkitLineClamp": "none",
    "webkitLocale": "\"en-US\"",
    "webkitLogicalHeight": "4622.47px",
    "webkitLogicalWidth": "2543px",
    "webkitMarginAfter": "0px",
    "webkitMarginBefore": "0px",
    "webkitMarginEnd": "0px",
    "webkitMarginStart": "0px",
    "webkitMask": "none",
    "webkitMaskBoxImage": "none",
    "webkitMaskBoxImageOutset": "0",
    "webkitMaskBoxImageRepeat": "stretch",
    "webkitMaskBoxImageSlice": "0 fill",
    "webkitMaskBoxImageSource": "none",
    "webkitMaskBoxImageWidth": "auto",
    "webkitMaskClip": "border-box",
    "webkitMaskComposite": "add",
    "webkitMaskImage": "none",
    "webkitMaskOrigin": "border-box",
    "webkitMaskPosition": "0% 0%",
    "webkitMaskPositionX": "0%",
    "webkitMaskPositionY": "0%",
    "webkitMaskRepeat": "repeat",
    "webkitMaskSize": "auto",
    "webkitMaxLogicalHeight": "none",
    "webkitMaxLogicalWidth": "none",
    "webkitMinLogicalHeight": "0px",
    "webkitMinLogicalWidth": "0px",
    "webkitOpacity": "1",
    "webkitOrder": "0",
    "webkitPaddingAfter": "0px",
    "webkitPaddingBefore": "0px",
    "webkitPaddingEnd": "0px",
    "webkitPaddingStart": "0px",
    "webkitPerspective": "none",
    "webkitPerspectiveOrigin": "1271.5px 2311.23px",
    "webkitPerspectiveOriginX": "",
    "webkitPerspectiveOriginY": "",
    "webkitPrintColorAdjust": "economy",
    "webkitRtlOrdering": "logical",
    "webkitRubyPosition": "before",
    "webkitShapeImageThreshold": "0",
    "webkitShapeMargin": "0px",
    "webkitShapeOutside": "none",
    "webkitTapHighlightColor": "rgba(0, 0, 0, 0.18)",
    "webkitTextCombine": "none",
    "webkitTextDecorationsInEffect": "none",
    "webkitTextEmphasis": "none rgb(255, 255, 255)",
    "webkitTextEmphasisColor": "rgb(255, 255, 255)",
    "webkitTextEmphasisPosition": "over",
    "webkitTextEmphasisStyle": "none",
    "webkitTextFillColor": "rgb(255, 255, 255)",
    "webkitTextOrientation": "vertical-right",
    "webkitTextSecurity": "none",
    "webkitTextSizeAdjust": "auto",
    "webkitTextStroke": "",
    "webkitTextStrokeColor": "rgb(255, 255, 255)",
    "webkitTextStrokeWidth": "0px",
    "webkitTransform": "none",
    "webkitTransformOrigin": "1271.5px 2311.23px",
    "webkitTransformOriginX": "",
    "webkitTransformOriginY": "",
    "webkitTransformOriginZ": "",
    "webkitTransformStyle": "flat",
    "webkitTransition": "all 1e-05s ease 0s",
    "webkitTransitionDelay": "0s",
    "webkitTransitionDuration": "1e-05s",
    "webkitTransitionProperty": "all",
    "webkitTransitionTimingFunction": "ease",
    "webkitUserDrag": "auto",
    "webkitUserModify": "read-only",
    "webkitUserSelect": "auto",
    "webkitWritingMode": "horizontal-tb",
    "whiteSpace": "normal",
    "whiteSpaceCollapse": "collapse",
    "widows": "2",
    "width": "2543px",
    "willChange": "auto",
    "wordBreak": "normal",
    "wordSpacing": "0px",
    "wordWrap": "normal",
    "writingMode": "horizontal-tb",
    "x": "0px",
    "y": "0px",
    "zIndex": "auto",
    "zoom": "1"
}
 * 
 */